import { Exercise, Routine, MuscleGroup } from './types';

export const INITIAL_EXERCISES: Exercise[] = [
  // --- PECHO (CHEST) ---
  { id: 'ch_1', name: 'Press de Banca con Barra', muscle: MuscleGroup.Chest, description: 'Básico de fuerza para todo el pectoral.' },
  { id: 'ch_2', name: 'Press de Banca Inclinado (Barra)', muscle: MuscleGroup.Chest, description: 'Enfoca la porción clavicular (superior).' },
  { id: 'ch_3', name: 'Press de Banca Declinado (Barra)', muscle: MuscleGroup.Chest, description: 'Enfoca la porción inferior.' },
  { id: 'ch_4', name: 'Press Plano con Mancuernas', muscle: MuscleGroup.Chest, description: 'Mayor rango de movimiento y estabilización.' },
  { id: 'ch_5', name: 'Press Inclinado con Mancuernas', muscle: MuscleGroup.Chest, description: 'Excelente para el pectoral superior.' },
  { id: 'ch_6', name: 'Press Declinado con Mancuernas', muscle: MuscleGroup.Chest, description: 'Variante libre para pectoral inferior.' },
  { id: 'ch_7', name: 'Press de Pecho en Máquina (Sentado)', muscle: MuscleGroup.Chest, description: 'Estabilidad máxima, ideal para hipertrofia segura.' },
  { id: 'ch_8', name: 'Press Inclinado en Máquina', muscle: MuscleGroup.Chest, description: 'Aislamiento seguro del pecho superior.' },
  { id: 'ch_9', name: 'Press de Pecho en Smith', muscle: MuscleGroup.Chest, description: 'Movimiento guiado para cargas altas.' },
  { id: 'ch_10', name: 'Press Inclinado en Smith', muscle: MuscleGroup.Chest, description: 'Enfoque superior con recorrido fijo.' },
  { id: 'ch_11', name: 'Aperturas (Flyes) con Mancuernas', muscle: MuscleGroup.Chest, description: 'Estiramiento bajo carga.' },
  { id: 'ch_12', name: 'Aperturas Inclinadas con Mancuernas', muscle: MuscleGroup.Chest, description: 'Estiramiento para la parte superior.' },
  { id: 'ch_13', name: 'Cruce de Poleas (Alto a Bajo)', muscle: MuscleGroup.Chest, description: 'Enfasis en zona baja y media.' },
  { id: 'ch_14', name: 'Cruce de Poleas (Bajo a Alto)', muscle: MuscleGroup.Chest, description: 'Enfasis en zona superior.' },
  { id: 'ch_15', name: 'Pec Deck (Contractora)', muscle: MuscleGroup.Chest, description: 'Aislamiento puro en acortamiento.' },
  { id: 'ch_16', name: 'Fondos en Paralelas (Pecho)', muscle: MuscleGroup.Chest, description: 'Torso inclinado adelante.' },
  { id: 'ch_17', name: 'Fondos en Máquina Asistida', muscle: MuscleGroup.Chest, description: 'Para ganar fuerza en el patrón de fondos.' },
  { id: 'ch_18', name: 'Flexiones (Push Ups)', muscle: MuscleGroup.Chest, description: 'Clásico peso corporal.' },
  { id: 'ch_19', name: 'Flexiones Diamante', muscle: MuscleGroup.Chest, description: 'Enfoque en tríceps y pecho interior.' },
  { id: 'ch_20', name: 'Flexiones con Déficit', muscle: MuscleGroup.Chest, description: 'Manos elevadas para mayor estiramiento.' },
  { id: 'ch_21', name: 'Pullover con Mancuerna', muscle: MuscleGroup.Chest, description: 'Trabaja pecho y dorsales en estiramiento.' },
  { id: 'ch_22', name: 'Press Svend', muscle: MuscleGroup.Chest, description: 'Tensión isométrica constante.' },
  { id: 'ch_23', name: 'Press Landmine (Unilateral)', muscle: MuscleGroup.Chest, description: 'Empuje angular para pecho superior.' },
  { id: 'ch_24', name: 'Hex Press (Mancuernas juntas)', muscle: MuscleGroup.Chest, description: 'Aprieta las mancuernas entre sí al subir.' },
  { id: 'ch_25', name: 'Press de Banca Agarre Inverso', muscle: MuscleGroup.Chest, description: 'Activación alta del haz clavicular.' },
  { id: 'ch_26', name: 'Flexiones Declinadas', muscle: MuscleGroup.Chest, description: 'Pies elevados, énfasis superior.' },
  { id: 'ch_27', name: 'Flexiones Inclinadas', muscle: MuscleGroup.Chest, description: 'Manos elevadas, énfasis inferior.' },
  { id: 'ch_28', name: 'Press Guillotina', muscle: MuscleGroup.Chest, description: 'Barra al cuello, codos abiertos (Cuidado).' },
  { id: 'ch_29', name: 'Fly en Polea a una mano', muscle: MuscleGroup.Chest, description: 'Mayor rango cruzando la línea media.' },
  { id: 'ch_30', name: 'Press Floor (Suelo) con Mancuernas', muscle: MuscleGroup.Chest, description: 'Limita el rango, énfasis tríceps/bloqueo.' },
  { id: 'ch_31', name: 'Press de Banca Agarre Cerrado', muscle: MuscleGroup.Chest, description: 'Tríceps y pecho interior.' },
  { id: 'ch_32', name: 'Flexiones Arqueras', muscle: MuscleGroup.Chest, description: 'Unilateral alterno.' },
  { id: 'ch_33', name: 'Flexiones Explosivas (Clap)', muscle: MuscleGroup.Chest, description: 'Potencia.' },
  { id: 'ch_34', name: 'Aperturas en Máquina Inclinada', muscle: MuscleGroup.Chest, description: 'Rara pero efectiva para superior.' },
  { id: 'ch_35', name: 'Press con Kettlebell', muscle: MuscleGroup.Chest, description: 'Inestabilidad añadida.' },

  // --- ESPALDA (BACK) ---
  { id: 'bk_1', name: 'Dominadas (Pull Ups)', muscle: MuscleGroup.Back, description: 'Agarre prono, anchura dorsal.' },
  { id: 'bk_2', name: 'Dominadas Supinas (Chin Ups)', muscle: MuscleGroup.Back, description: 'Agarre supino, mayor bíceps.' },
  { id: 'bk_3', name: 'Dominadas Neutras', muscle: MuscleGroup.Back, description: 'Agarre martillo, braquial y dorsal.' },
  { id: 'bk_4', name: 'Jalón al Pecho (Agarre Ancho)', muscle: MuscleGroup.Back, description: 'Sustituto de dominadas para anchura.' },
  { id: 'bk_5', name: 'Jalón al Pecho (Agarre Supino)', muscle: MuscleGroup.Back, description: 'Enfasis en dorsal bajo y bíceps.' },
  { id: 'bk_6', name: 'Jalón al Pecho (Agarre V/Estrecho)', muscle: MuscleGroup.Back, description: 'Enfasis en zona media de la espalda.' },
  { id: 'bk_7', name: 'Remo con Barra (Bent Over Row)', muscle: MuscleGroup.Back, description: 'Constructor de masa general.' },
  { id: 'bk_8', name: 'Remo Pendlay', muscle: MuscleGroup.Back, description: 'Estricto desde el suelo, potencia.' },
  { id: 'bk_9', name: 'Remo Yates', muscle: MuscleGroup.Back, description: 'Más vertical, agarre supino.' },
  { id: 'bk_10', name: 'Remo con Mancuerna (Unilateral)', muscle: MuscleGroup.Back, description: 'Apoyo en banco, rango largo.' },
  { id: 'bk_11', name: 'Remo Gironda (Polea Baja)', muscle: MuscleGroup.Back, description: 'Remo sentado al abdomen.' },
  { id: 'bk_12', name: 'Remo en Punta (T-Bar Row)', muscle: MuscleGroup.Back, description: 'Carga pesada, agarre neutro o prono.' },
  { id: 'bk_13', name: 'Remo en Máquina (Pecho apoyado)', muscle: MuscleGroup.Back, description: 'Aísla la espalda sin cargar lumbares.' },
  { id: 'bk_14', name: 'Peso Muerto Convencional', muscle: MuscleGroup.Back, description: 'Cadena posterior completa.' },
  { id: 'bk_15', name: 'Peso Muerto Rack Pull', muscle: MuscleGroup.Back, description: 'Parcial desde rodillas, densidad alta.' },
  { id: 'bk_16', name: 'Pullover en Polea Alta', muscle: MuscleGroup.Back, description: 'Aislamiento del dorsal en extensión.' },
  { id: 'bk_17', name: 'Face Pull', muscle: MuscleGroup.Back, description: 'Salud del hombro, trapecio y deltoides posterior.' },
  { id: 'bk_18', name: 'Remo al Mentón (Upright Row)', muscle: MuscleGroup.Back, description: 'Trapecios y deltoides laterales.' },
  { id: 'bk_19', name: 'Encogimientos con Barra (Shrugs)', muscle: MuscleGroup.Back, description: 'Trapecio superior.' },
  { id: 'bk_20', name: 'Encogimientos con Mancuernas', muscle: MuscleGroup.Back, description: 'Trapecio superior, neutro.' },
  { id: 'bk_21', name: 'Hiperextensiones (Lumbares)', muscle: MuscleGroup.Back, description: 'Erectores espinales.' },
  { id: 'bk_22', name: 'Good Morning', muscle: MuscleGroup.Back, description: 'Cadena posterior, isquios y lumbares.' },
  { id: 'bk_23', name: 'Remo Kroc', muscle: MuscleGroup.Back, description: 'Mancuerna pesada, altas repeticiones.' },
  { id: 'bk_24', name: 'Jalón Unilateral en Polea', muscle: MuscleGroup.Back, description: 'Mejor contracción lateral.' },
  { id: 'bk_25', name: 'Remo Meadows', muscle: MuscleGroup.Back, description: 'Landmine unilateral, codo afuera.' },
  { id: 'bk_26', name: 'Seal Row (Remo Foca)', muscle: MuscleGroup.Back, description: 'Tumbado en banco alto, aislamiento total.' },
  { id: 'bk_27', name: 'Remo Invertido (Australian Pullup)', muscle: MuscleGroup.Back, description: 'Peso corporal bajo barra.' },
  { id: 'bk_28', name: 'Jalón tras nuca', muscle: MuscleGroup.Back, description: 'Cuidado con el hombro, buena aducción.' },
  { id: 'bk_29', name: 'Dominadas Asistidas (Máquina)', muscle: MuscleGroup.Back, description: 'Para progresar a libres.' },
  { id: 'bk_30', name: 'Superman (Suelo)', muscle: MuscleGroup.Back, description: 'Isométrico lumbar.' },
  { id: 'bk_31', name: 'Jalón con brazos rectos', muscle: MuscleGroup.Back, description: 'Aislamiento dorsal.' },
  { id: 'bk_32', name: 'Remo Renegado', muscle: MuscleGroup.Back, description: 'Plancha con mancuernas.' },
  { id: 'bk_33', name: 'Pullover con Mancuerna', muscle: MuscleGroup.Back, description: 'Dorsal y serratos.' },

  // --- PIERNAS - CUADRICEPS (LEGS) ---
  { id: 'lg_1', name: 'Sentadilla Trasera (Barra Alta)', muscle: MuscleGroup.Legs, description: 'Enfoque en cuádriceps.' },
  { id: 'lg_2', name: 'Sentadilla Trasera (Barra Baja)', muscle: MuscleGroup.Legs, description: 'Enfoque en cadena posterior.' },
  { id: 'lg_3', name: 'Sentadilla Frontal', muscle: MuscleGroup.Legs, description: 'Torso vertical, máximo cuádriceps.' },
  { id: 'lg_4', name: 'Sentadilla Goblet', muscle: MuscleGroup.Legs, description: 'Mancuerna al pecho.' },
  { id: 'lg_5', name: 'Prensa de Piernas (45 grados)', muscle: MuscleGroup.Legs, description: 'Carga alta sin columna.' },
  { id: 'lg_6', name: 'Sentadilla Hack', muscle: MuscleGroup.Legs, description: 'Guiada, excelente para vastos.' },
  { id: 'lg_7', name: 'Extensión de Cuádriceps', muscle: MuscleGroup.Legs, description: 'Aislamiento en posición sentada.' },
  { id: 'lg_8', name: 'Zancadas (Walking Lunges)', muscle: MuscleGroup.Legs, description: 'Dinámicas avanzando.' },
  { id: 'lg_9', name: 'Zancadas Estáticas', muscle: MuscleGroup.Legs, description: 'Sin desplazamiento.' },
  { id: 'lg_10', name: 'Zancadas Traseras (Reverse)', muscle: MuscleGroup.Legs, description: 'Menos impacto en rodilla.' },
  { id: 'lg_11', name: 'Sentadilla Búlgara', muscle: MuscleGroup.Legs, description: 'Unilateral con pie elevado.' },
  { id: 'lg_12', name: 'Step Up al cajón', muscle: MuscleGroup.Legs, description: 'Unilateral, subida a banco.' },
  { id: 'lg_13', name: 'Sentadilla Sissy', muscle: MuscleGroup.Legs, description: 'Estiramiento máximo del recto femoral.' },
  { id: 'lg_14', name: 'Sentadilla Pistol', muscle: MuscleGroup.Legs, description: 'Una pierna, equilibrio.' },
  { id: 'lg_15', name: 'Prensa Horizontal', muscle: MuscleGroup.Legs, description: 'Variante en máquina de placas.' },
  { id: 'lg_16', name: 'Sentadilla Sumo (Mancuerna)', muscle: MuscleGroup.Legs, description: 'Pies abiertos, aductores.' },
  { id: 'lg_17', name: 'Sentadilla Zercher', muscle: MuscleGroup.Legs, description: 'Barra en antebrazos, core y quads.' },
  { id: 'lg_18', name: 'Sentadilla Smith', muscle: MuscleGroup.Legs, description: 'Guiada, permite pies adelantados.' },
  { id: 'lg_19', name: 'Saltos al Cajón (Box Jump)', muscle: MuscleGroup.Legs, description: 'Potencia explosiva.' },
  { id: 'lg_20', name: 'Wall Sit (Sentadilla isométrica)', muscle: MuscleGroup.Legs, description: 'Resistencia contra pared.' },
  { id: 'lg_21', name: 'Sentadilla Ciclista', muscle: MuscleGroup.Legs, description: 'Talones muy elevados.' },
  { id: 'lg_22', name: 'Prensa Unilateral', muscle: MuscleGroup.Legs, description: 'Corregir asimetrías.' },
  { id: 'lg_23', name: 'Sentadilla Anderson', muscle: MuscleGroup.Legs, description: 'Desde parada en pines bajos.' },

  // --- PIERNAS - ISQUIOS (LEGS) ---
  { id: 'hm_1', name: 'Peso Muerto Rumano (Barra)', muscle: MuscleGroup.Legs, description: 'Cadera atrás, rodillas semi-rígidas.' },
  { id: 'hm_2', name: 'Peso Muerto Rumano (Mancuernas)', muscle: MuscleGroup.Legs, description: 'Mayor libertad lateral.' },
  { id: 'hm_3', name: 'Curl Femoral Tumbado', muscle: MuscleGroup.Legs, description: 'Flexión de rodilla pura.' },
  { id: 'hm_4', name: 'Curl Femoral Sentado', muscle: MuscleGroup.Legs, description: 'Isquios en estiramiento.' },
  { id: 'hm_5', name: 'Peso Muerto Piernas Rígidas', muscle: MuscleGroup.Legs, description: 'Mayor estiramiento que el rumano.' },
  { id: 'hm_6', name: 'Curl Nórdico', muscle: MuscleGroup.Legs, description: 'Excéntrico puro, muy difícil.' },
  { id: 'hm_7', name: 'Curl Femoral de Pie (Máquina)', muscle: MuscleGroup.Legs, description: 'Unilateral.' },
  { id: 'hm_8', name: 'Glute Ham Raise (GHR)', muscle: MuscleGroup.Legs, description: 'Cadena posterior completa.' },
  { id: 'hm_9', name: 'Deslizamientos de Isquios (Suelo)', muscle: MuscleGroup.Legs, description: 'Con toalla o deslizadores.' },
  { id: 'hm_10', name: 'Swing con Kettlebell', muscle: MuscleGroup.Legs, description: 'Bisagra de cadera explosiva.' },
  { id: 'hm_11', name: 'Peso Muerto Unilateral', muscle: MuscleGroup.Legs, description: 'Equilibrio e isquios.' },
  { id: 'hm_12', name: 'Gemelo de Pie (Máquina)', muscle: MuscleGroup.Legs, description: 'Gastrocnemio.' },
  { id: 'hm_13', name: 'Gemelo Sentado (Máquina)', muscle: MuscleGroup.Legs, description: 'Sóleo.' },
  { id: 'hm_14', name: 'Gemelo en Prensa', muscle: MuscleGroup.Legs, description: 'Carga alta.' },
  { id: 'hm_15', name: 'Gemelo tipo Burro', muscle: MuscleGroup.Legs, description: 'Estiramiento profundo.' },

  // --- GLUTEOS (GLUTES) ---
  { id: 'gl_1', name: 'Hip Thrust con Barra', muscle: MuscleGroup.Glutes, description: 'El mejor constructor de glúteo.' },
  { id: 'gl_2', name: 'Hip Thrust en Máquina', muscle: MuscleGroup.Glutes, description: 'Fácil configuración.' },
  { id: 'gl_3', name: 'Puente de Glúteo (Suelo)', muscle: MuscleGroup.Glutes, description: 'Sin banco, rango corto.' },
  { id: 'gl_4', name: 'Kas Glute Bridge', muscle: MuscleGroup.Glutes, description: 'Hip thrust rango parcial arriba.' },
  { id: 'gl_5', name: 'Patada de Glúteo en Polea', muscle: MuscleGroup.Glutes, description: 'Extensión de cadera cable.' },
  { id: 'gl_6', name: 'Patada de Glúteo Máquina', muscle: MuscleGroup.Glutes, description: 'Trayectoria fija.' },
  { id: 'gl_7', name: 'Hiperextensiones 45º (Enfoque Glúteo)', muscle: MuscleGroup.Glutes, description: 'Espalda redonda, empuja cadera.' },
  { id: 'gl_8', name: 'Abducción en Máquina', muscle: MuscleGroup.Glutes, description: 'Glúteo medio y menor.' },
  { id: 'gl_9', name: 'Abducción con Polea', muscle: MuscleGroup.Glutes, description: 'De pie, lateral.' },
  { id: 'gl_10', name: 'Peso Muerto Sumo', muscle: MuscleGroup.Glutes, description: 'Pies anchos, glúteo dominante.' },
  { id: 'gl_11', name: 'Frog Pumps', muscle: MuscleGroup.Glutes, description: 'Plantas juntas, bombeo.' },
  { id: 'gl_12', name: 'Step Up Cruzado (Curtsy)', muscle: MuscleGroup.Glutes, description: 'Enfoque glúteo medio.' },
  { id: 'gl_13', name: 'Caminata Lateral con Banda', muscle: MuscleGroup.Glutes, description: 'Activación glúteo medio.' },
  { id: 'gl_14', name: 'Pull Through en Polea', muscle: MuscleGroup.Glutes, description: 'Bisagra de cadera cable entre piernas.' },
  { id: 'gl_15', name: 'Single Leg Hip Thrust', muscle: MuscleGroup.Glutes, description: 'Unilateral, corrección de asimetrías.' },
  { id: 'gl_16', name: 'Reverse Hyperextension', muscle: MuscleGroup.Glutes, description: 'Piernas suben, torso fijo.' },
  { id: 'gl_17', name: 'Zancada Reverencia (Curtsy Lunge)', muscle: MuscleGroup.Glutes, description: 'Cruce por detrás.' },
  { id: 'gl_18', name: 'Donkey Kicks (Peso corporal)', muscle: MuscleGroup.Glutes, description: 'Patada burro en suelo.' },
  { id: 'gl_19', name: 'Clamshells', muscle: MuscleGroup.Glutes, description: 'Apertura lateral tumbado.' },
  { id: 'gl_20', name: 'Sentadilla de Rodillas (Kneeling Squat)', muscle: MuscleGroup.Glutes, description: 'Enfasis en extensión final.' },
  { id: 'gl_21', name: 'Good Morning Sentado', muscle: MuscleGroup.Glutes, description: 'Desde banco.' },
  { id: 'gl_22', name: 'Hip Thrust Unilateral (Mancuerna)', muscle: MuscleGroup.Glutes, description: 'Intensidad media.' },

  // --- HOMBROS (SHOULDERS) ---
  { id: 'sh_1', name: 'Press Militar (Barra de pie)', muscle: MuscleGroup.Shoulders, description: 'Fuerza global.' },
  { id: 'sh_2', name: 'Press Militar Sentado (Barra)', muscle: MuscleGroup.Shoulders, description: 'Sin impulso de piernas.' },
  { id: 'sh_3', name: 'Press con Mancuernas Sentado', muscle: MuscleGroup.Shoulders, description: 'Estabilidad y rango.' },
  { id: 'sh_4', name: 'Press Arnold', muscle: MuscleGroup.Shoulders, description: 'Rotación, trabaja todas las cabezas.' },
  { id: 'sh_5', name: 'Press tras nuca', muscle: MuscleGroup.Shoulders, description: 'Mayor activación lateral (cuidado).' },
  { id: 'sh_6', name: 'Press de Hombros en Máquina', muscle: MuscleGroup.Shoulders, description: 'Seguro y estable.' },
  { id: 'sh_7', name: 'Elevaciones Laterales Mancuernas', muscle: MuscleGroup.Shoulders, description: 'Cabeza lateral (anchura).' },
  { id: 'sh_8', name: 'Elevaciones Laterales Polea', muscle: MuscleGroup.Shoulders, description: 'Tensión constante.' },
  { id: 'sh_9', name: 'Elevaciones Laterales Máquina', muscle: MuscleGroup.Shoulders, description: 'Aislamiento estricto.' },
  { id: 'sh_10', name: 'Elevaciones Frontales Mancuernas', muscle: MuscleGroup.Shoulders, description: 'Cabeza anterior.' },
  { id: 'sh_11', name: 'Elevaciones Frontales Barra', muscle: MuscleGroup.Shoulders, description: 'Cabeza anterior.' },
  { id: 'sh_12', name: 'Elevaciones Frontales Disco', muscle: MuscleGroup.Shoulders, description: 'Agarre neutro.' },
  { id: 'sh_13', name: 'Pájaros (Rear Delt Fly) Mancuernas', muscle: MuscleGroup.Shoulders, description: 'Deltoides posterior.' },
  { id: 'sh_14', name: 'Pájaros en Máquina (Peck Deck Inverso)', muscle: MuscleGroup.Shoulders, description: 'Posterior estable.' },
  { id: 'sh_15', name: 'Face Pull', muscle: MuscleGroup.Shoulders, description: 'Posterior y rotadores.' },
  { id: 'sh_16', name: 'Remo al Mentón (Barra Z)', muscle: MuscleGroup.Shoulders, description: 'Lateral y trapecio.' },
  { id: 'sh_17', name: 'Lu Raises', muscle: MuscleGroup.Shoulders, description: 'Lateral rango completo hasta arriba.' },
  { id: 'sh_18', name: 'Y-Raises (Banco inclinado)', muscle: MuscleGroup.Shoulders, description: 'Trapecio inferior y hombro.' },
  { id: 'sh_19', name: 'Press Landmine (Hombro)', muscle: MuscleGroup.Shoulders, description: 'Empuje unilateral seguro.' },
  { id: 'sh_20', name: 'Egyptian Lateral Raise', muscle: MuscleGroup.Shoulders, description: 'Lateral polea inclinado.' },
  { id: 'sh_21', name: 'Press Z (Sentado suelo)', muscle: MuscleGroup.Shoulders, description: 'Requiere mucha estabilidad core.' },
  { id: 'sh_22', name: 'Bradford Press', muscle: MuscleGroup.Shoulders, description: 'Tensión constante sin bloqueo.' },
  { id: 'sh_23', name: 'Around the World', muscle: MuscleGroup.Shoulders, description: 'Movimiento circular completo.' },
  { id: 'sh_24', name: 'Bus Driver', muscle: MuscleGroup.Shoulders, description: 'Giro de disco al frente.' },

  // --- BRAZOS - BICEPS (ARMS) ---
  { id: 'bi_1', name: 'Curl con Barra (De pie)', muscle: MuscleGroup.Arms, description: 'Carga máxima.' },
  { id: 'bi_2', name: 'Curl con Barra Z', muscle: MuscleGroup.Arms, description: 'Mejor para muñecas.' },
  { id: 'bi_3', name: 'Curl con Mancuernas (Supinación)', muscle: MuscleGroup.Arms, description: 'Giro de muñeca.' },
  { id: 'bi_4', name: 'Curl Martillo', muscle: MuscleGroup.Arms, description: 'Braquial y antebrazo.' },
  { id: 'bi_5', name: 'Curl Predicador (Barra Z)', muscle: MuscleGroup.Arms, description: 'Aislamiento estricto banco Scott.' },
  { id: 'bi_6', name: 'Curl Predicador (Máquina)', muscle: MuscleGroup.Arms, description: 'Tensión constante.' },
  { id: 'bi_7', name: 'Curl Concentrado', muscle: MuscleGroup.Arms, description: 'Unilateral sentado.' },
  { id: 'bi_8', name: 'Curl Inclinado con Mancuernas', muscle: MuscleGroup.Arms, description: 'Cabeza larga en estiramiento.' },
  { id: 'bi_9', name: 'Curl Araña (Spider Curl)', muscle: MuscleGroup.Arms, description: 'Pecho apoyado, énfasis pico.' },
  { id: 'bi_10', name: 'Curl Bayesiando (Polea)', muscle: MuscleGroup.Arms, description: 'De espaldas a la polea.' },
  { id: 'bi_11', name: 'Curl 21', muscle: MuscleGroup.Arms, description: '7 parciales bajos, 7 altos, 7 completos.' },
  { id: 'bi_12', name: 'Curl Zottman', muscle: MuscleGroup.Arms, description: 'Sube supino, baja prono.' },
  { id: 'bi_13', name: 'Curl Polea Baja', muscle: MuscleGroup.Arms, description: 'Tensión fluida.' },
  { id: 'bi_14', name: 'Dominadas Supinas (Bíceps)', muscle: MuscleGroup.Arms, description: 'Compuesto para bíceps.' },
  { id: 'bi_15', name: 'Curl de Muñeca', muscle: MuscleGroup.Arms, description: 'Antebrazo flexor.' },
  { id: 'bi_16', name: 'Curl de Muñeca Inverso', muscle: MuscleGroup.Arms, description: 'Antebrazo extensor.' },
  { id: 'bi_17', name: 'Curl con Barra Inverso', muscle: MuscleGroup.Arms, description: 'Braquiorradial.' },
  { id: 'bi_18', name: 'Waiters Curl', muscle: MuscleGroup.Arms, description: 'Mancuerna vertical.' },

  // --- BRAZOS - TRICEPS (ARMS) ---
  { id: 'tri_1', name: 'Extensiones de Tríceps Polea (Cuerda)', muscle: MuscleGroup.Arms, description: 'Cabeza lateral.' },
  { id: 'tri_2', name: 'Extensiones de Tríceps Polea (Barra)', muscle: MuscleGroup.Arms, description: 'Carga pesada.' },
  { id: 'tri_3', name: 'Press Francés (Skullcrushers)', muscle: MuscleGroup.Arms, description: 'Cabeza larga y media.' },
  { id: 'tri_4', name: 'Press Banca Agarre Cerrado', muscle: MuscleGroup.Arms, description: 'Compuesto pesado.' },
  { id: 'tri_5', name: 'Fondos en Paralelas (Tríceps)', muscle: MuscleGroup.Arms, description: 'Torso vertical.' },
  { id: 'tri_6', name: 'Extensiones Tras Nuca (Mancuerna)', muscle: MuscleGroup.Arms, description: 'Estiramiento cabeza larga.' },
  { id: 'tri_7', name: 'Extensiones Tras Nuca (Polea)', muscle: MuscleGroup.Arms, description: 'Katana extensions.' },
  { id: 'tri_8', name: 'Patada de Tríceps (Mancuerna)', muscle: MuscleGroup.Arms, description: 'Contracción pico.' },
  { id: 'tri_9', name: 'Patada de Tríceps (Polea)', muscle: MuscleGroup.Arms, description: 'Tensión constante.' },
  { id: 'tri_10', name: 'Fondos entre bancos', muscle: MuscleGroup.Arms, description: 'Fácil ejecución.' },
  { id: 'tri_11', name: 'JM Press', muscle: MuscleGroup.Arms, description: 'Híbrido press/extensión.' },
  { id: 'tri_12', name: 'Tate Press', muscle: MuscleGroup.Arms, description: 'Codos afuera, pecho.' },
  { id: 'tri_13', name: 'Pushdown Unilateral', muscle: MuscleGroup.Arms, description: 'Agarre supino o neutro.' },
  { id: 'tri_14', name: 'Extensiones en Máquina', muscle: MuscleGroup.Arms, description: 'Sentado.' },
  { id: 'tri_15', name: 'Flexiones Diamante', muscle: MuscleGroup.Arms, description: 'Peso corporal.' },
  { id: 'tri_16', name: 'Rolling Triceps Extension', muscle: MuscleGroup.Arms, description: 'Mancuernas tumbado.' },

  // --- ABDOMINALES (CORE) ---
  { id: 'ab_1', name: 'Crunch Abdominal (Suelo)', muscle: MuscleGroup.Core, description: 'Flexión espinal básica.' },
  { id: 'ab_2', name: 'Crunch en Polea Alta', muscle: MuscleGroup.Core, description: 'Con carga.' },
  { id: 'ab_3', name: 'Elevación de Piernas (Colgado)', muscle: MuscleGroup.Core, description: 'Abdomen inferior.' },
  { id: 'ab_4', name: 'Elevación de Rodillas (Capitán Silla)', muscle: MuscleGroup.Core, description: 'Más fácil que colgado.' },
  { id: 'ab_5', name: 'Plancha Abdominal (Plank)', muscle: MuscleGroup.Core, description: 'Isométrico.' },
  { id: 'ab_6', name: 'Plancha Lateral', muscle: MuscleGroup.Core, description: 'Oblicuos.' },
  { id: 'ab_7', name: 'Rueda Abdominal (Ab Wheel)', muscle: MuscleGroup.Core, description: 'Anti-extensión intensa.' },
  { id: 'ab_8', name: 'Russian Twist', muscle: MuscleGroup.Core, description: 'Rotación con peso.' },
  { id: 'ab_9', name: 'Woodchoppers (Leñador)', muscle: MuscleGroup.Core, description: 'Rotación en polea.' },
  { id: 'ab_10', name: 'Hollow Body Hold', muscle: MuscleGroup.Core, description: 'Isométrico gimnasta.' },
  { id: 'ab_11', name: 'Dragon Flag', muscle: MuscleGroup.Core, description: 'Avanzado, estilo Bruce Lee.' },
  { id: 'ab_12', name: 'V-Ups', muscle: MuscleGroup.Core, description: 'Navaja.' },
  { id: 'ab_13', name: 'Mountain Climbers', muscle: MuscleGroup.Core, description: 'Dinámico.' },
  { id: 'ab_14', name: 'Dead Bug', muscle: MuscleGroup.Core, description: 'Coordinación y core profundo.' },
  { id: 'ab_15', name: 'Pallof Press', muscle: MuscleGroup.Core, description: 'Anti-rotación.' },
  { id: 'ab_16', name: 'L-Sit', muscle: MuscleGroup.Core, description: 'Estático avanzado.' },
  { id: 'ab_17', name: 'Sit Ups', muscle: MuscleGroup.Core, description: 'Levantamiento completo.' },
  { id: 'ab_18', name: 'Crunch Inverso', muscle: MuscleGroup.Core, description: 'Cadera hacia costillas.' },
  { id: 'ab_19', name: 'Toes to Bar', muscle: MuscleGroup.Core, description: 'Pies a la barra.' },
  { id: 'ab_20', name: 'Vacuum Abdominal', muscle: MuscleGroup.Core, description: 'Transverso.' },

  // --- CARDIO ---
  { id: 'cd_1', name: 'Cinta de Correr (Running)', muscle: MuscleGroup.Cardio, description: 'Carrera continua o intervalos.' },
  { id: 'cd_2', name: 'Cinta (Caminata Inclinada)', muscle: MuscleGroup.Cardio, description: 'Bajo impacto, quema calórica.' },
  { id: 'cd_3', name: 'Bicicleta Estática', muscle: MuscleGroup.Cardio, description: 'Cardio sentado.' },
  { id: 'cd_4', name: 'Elíptica', muscle: MuscleGroup.Cardio, description: 'Sin impacto articular.' },
  { id: 'cd_5', name: 'Remo (Concept 2)', muscle: MuscleGroup.Cardio, description: 'Cardio cuerpo completo.' },
  { id: 'cd_6', name: 'Escaladora (Stairmaster)', muscle: MuscleGroup.Cardio, description: 'Glúteos y piernas.' },
  { id: 'cd_7', name: 'Salto a la Comba', muscle: MuscleGroup.Cardio, description: 'Coordinación y gemelos.' },
  { id: 'cd_8', name: 'Assault Bike (Air Bike)', muscle: MuscleGroup.Cardio, description: 'HIIT intenso.' },
  { id: 'cd_9', name: 'Burpees', muscle: MuscleGroup.Cardio, description: 'Metabólico.' },
  { id: 'cd_10', name: 'Saco de Boxeo', muscle: MuscleGroup.Cardio, description: 'Golpes y movimiento.' },
  { id: 'cd_11', name: 'Natación', muscle: MuscleGroup.Cardio, description: 'Cuerpo completo agua.' },
  { id: 'cd_12', name: 'SkiErg', muscle: MuscleGroup.Cardio, description: 'Tiro superior.' },
  { id: 'cd_13', name: 'Sprints', muscle: MuscleGroup.Cardio, description: 'Velocidad máxima.' },

  // --- EN CASA (HOME) ---
  { id: 'hm_ex1', name: 'Flexiones', muscle: MuscleGroup.Home, description: 'Pecho en suelo.' },
  { id: 'hm_ex2', name: 'Sentadilla al aire', muscle: MuscleGroup.Home, description: 'Piernas.' },
  { id: 'hm_ex3', name: 'Zancadas estáticas', muscle: MuscleGroup.Home, description: 'Piernas.' },
  { id: 'hm_ex4', name: 'Fondos en silla', muscle: MuscleGroup.Home, description: 'Tríceps.' },
  { id: 'hm_ex5', name: 'Remo con Mochila/Agua', muscle: MuscleGroup.Home, description: 'Espalda casera.' },
  { id: 'hm_ex6', name: 'Curl de Bíceps (Banda)', muscle: MuscleGroup.Home, description: 'Elástico.' },
  { id: 'hm_ex7', name: 'Aperturas de Hombro (Banda)', muscle: MuscleGroup.Home, description: 'Hombros.' },
  { id: 'hm_ex8', name: 'Jumping Jacks', muscle: MuscleGroup.Home, description: 'Cardio.' },
  { id: 'hm_ex9', name: 'Sentadilla con Salto', muscle: MuscleGroup.Home, description: 'Potencia.' },
  { id: 'hm_ex10', name: 'Plancha suelo', muscle: MuscleGroup.Home, description: 'Core.' },
  { id: 'hm_ex11', name: 'Escaladores (Suelo)', muscle: MuscleGroup.Home, description: 'Cardio core.' },
  { id: 'hm_ex12', name: 'Puente Glúteo (Suelo)', muscle: MuscleGroup.Home, description: 'Glúteo.' },
  { id: 'hm_ex13', name: 'Paso del Oso', muscle: MuscleGroup.Home, description: 'Cuerpo completo.' },
  { id: 'hm_ex14', name: 'Sentadilla Pistol Asistida', muscle: MuscleGroup.Home, description: 'Con marco de puerta.' },
  { id: 'hm_ex15', name: 'Flexiones en Pica', muscle: MuscleGroup.Home, description: 'Hombros.' },

  // --- OTROS (OTHER / CROSSFIT / OLYMPIC) ---
  { id: 'ot_1', name: 'Clean & Jerk', muscle: MuscleGroup.Other, description: 'Olimpico dos tiempos.' },
  { id: 'ot_2', name: 'Snatch (Arrancada)', muscle: MuscleGroup.Other, description: 'Olimpico un tiempo.' },
  { id: 'ot_3', name: 'Farmer Walk (Paseo Granjero)', muscle: MuscleGroup.Other, description: 'Agarre y trapecios.' },
  { id: 'ot_4', name: 'Battle Ropes', muscle: MuscleGroup.Other, description: 'Acondicionamiento.' },
  { id: 'ot_5', name: 'Sled Push (Empuje Trineo)', muscle: MuscleGroup.Other, description: 'Piernas y cardio.' },
  { id: 'ot_6', name: 'Clean (Cargada)', muscle: MuscleGroup.Other, description: 'Fase 1 del C&J.' },
  { id: 'ot_7', name: 'Jerk (Envión)', muscle: MuscleGroup.Other, description: 'Fase 2 del C&J.' },
  { id: 'ot_8', name: 'Thrusters', muscle: MuscleGroup.Other, description: 'Sentadilla + Press.' },
  { id: 'ot_9', name: 'Wall Ball', muscle: MuscleGroup.Other, description: 'Balón a pared.' },
  { id: 'ot_10', name: 'Turkish Get Up', muscle: MuscleGroup.Other, description: 'Levantada turca.' },
  { id: 'ot_11', name: 'Kettlebell Snatch', muscle: MuscleGroup.Other, description: 'Arrancada pesa rusa.' },
  { id: 'ot_12', name: 'Muscle Up (Barra)', muscle: MuscleGroup.Other, description: 'Dominada + Fondo.' },
  { id: 'ot_13', name: 'Muscle Up (Anillas)', muscle: MuscleGroup.Other, description: 'Gimnasia avanzada.' },
  { id: 'ot_14', name: 'Handstand Push Ups', muscle: MuscleGroup.Other, description: 'Flexiones pino.' },
  { id: 'ot_15', name: 'Tire Flip', muscle: MuscleGroup.Other, description: 'Volteo neumático.' }
];

export const INITIAL_ROUTINES: Routine[] = [
  // --- GYM ROUTINES ---
  {
    id: 'r1',
    name: 'Torso Fuerza (Gym)',
    color: 'bg-blue-500',
    description: 'Pecho y Espalda pesados.',
    isHome: false,
    exercises: [
      { exerciseId: 'ch_1', targetSets: 4, targetReps: '6-8' },
      { exerciseId: 'bk_8', targetSets: 4, targetReps: '6-8' },
      { exerciseId: 'sh_1', targetSets: 3, targetReps: '8-10' },
      { exerciseId: 'ch_16', targetSets: 3, targetReps: 'Fallo' },
    ],
  },
  {
    id: 'r2',
    name: 'Pierna & Glúteo (Gym)',
    color: 'bg-rose-500',
    description: 'Enfoque en desarrollo de tren inferior.',
    isHome: false,
    exercises: [
      { exerciseId: 'gl_1', targetSets: 4, targetReps: '8-12' },
      { exerciseId: 'lg_1', targetSets: 3, targetReps: '8-10' },
      { exerciseId: 'lg_11', targetSets: 3, targetReps: '10-12' },
      { exerciseId: 'gl_5', targetSets: 3, targetReps: '15-20' },
      { exerciseId: 'hm_1', targetSets: 3, targetReps: '10-12' },
    ],
  },
  {
    id: 'r3',
    name: 'Full Body (Gym)',
    color: 'bg-purple-500',
    description: 'Frecuencia alta, un poco de todo.',
    isHome: false,
    exercises: [
      { exerciseId: 'lg_5', targetSets: 3, targetReps: '10' },
      { exerciseId: 'ch_4', targetSets: 3, targetReps: '10' },
      { exerciseId: 'bk_4', targetSets: 3, targetReps: '10' },
      { exerciseId: 'sh_3', targetSets: 3, targetReps: '12' },
      { exerciseId: 'bi_1', targetSets: 3, targetReps: '12' },
    ],
  },

  // --- HOME ROUTINES ---
  {
    id: 'h1',
    name: 'En Casa: Full Body',
    color: 'bg-orange-500',
    description: 'Entrena todo el cuerpo sin material.',
    isHome: true,
    exercises: [
      { exerciseId: 'hm_ex8', targetSets: 2, targetReps: '50' },
      { exerciseId: 'hm_ex2', targetSets: 4, targetReps: '15-20' },
      { exerciseId: 'hm_ex1', targetSets: 3, targetReps: 'Fallo' },
      { exerciseId: 'hm_ex3', targetSets: 3, targetReps: '12/pierna' },
      { exerciseId: 'hm_ex4', targetSets: 3, targetReps: '12-15' },
      { exerciseId: 'hm_ex10', targetSets: 3, targetReps: '45s' },
    ],
  },
  {
    id: 'h2',
    name: 'En Casa: Glúteos de Acero',
    color: 'bg-pink-500',
    description: 'Tonificación y fuerza de glúteo en el salón.',
    isHome: true,
    exercises: [
      { exerciseId: 'gl_3', targetSets: 4, targetReps: '20' },
      { exerciseId: 'gl_18', targetSets: 4, targetReps: '15/pierna' },
      { exerciseId: 'lg_11', targetSets: 3, targetReps: '10-12' },
      { exerciseId: 'gl_11', targetSets: 3, targetReps: '30' },
      { exerciseId: 'hm_ex9', targetSets: 3, targetReps: '15' },
    ],
  },
];